export const data = [
  {
    id: 1,
    fromAddress: "456 Park Rd, Chicago",
    deliveryAddress: "123 Park Rd, Chicago",
    container: "40 f",
    weight: 63,
    price: 286,
    status: false,
  },
  {
    id: 2,
    fromAddress: "789 First St, Houston",
    deliveryAddress: "123 Oak Ave, Chicago",
    container: "20 f + 20 f",
    weight: 78,
    price: 854,
    status: true,
  },
  {
    id: 3,
    fromAddress: "456 Oak Ave, Houston",
    deliveryAddress: "456 First St, Chicago",
    container: "20 f",
    weight: 1,
    price: 407,
    status: false,
  },
  {
    id: 4,
    fromAddress: "123 Oak Ave, Los Angeles",
    deliveryAddress: "789 First St, Chicago",
    container: "20 f",
    weight: 73,
    price: 492,
    status: true,
  },
  {
    id: 5,
    fromAddress: "456 First St, Chicago",
    deliveryAddress: "123 Oak Ave, New York",
    container: "20 f + 20 f",
    weight: 24,
    price: 104,
    status: false,
  },
  {
    id: 6,
    fromAddress: "789 Park Rd, Chicago",
    deliveryAddress: "789 Oak Ave, New York",
    container: "20 f + 20 f",
    weight: 50,
    price: 327,
    status: true,
  },
  {
    id: 7,
    fromAddress: "456 Main St, Los Angeles",
    deliveryAddress: "789 First St, Houston",
    container: "20 f + 20 f",
    weight: 40,
    price: 139,
    status: true,
  },
  {
    id: 8,
    fromAddress: "789 First St, Los Angeles",
    deliveryAddress: "456 Main St, Houston",
    container: "20 f",
    weight: 62,
    price: 525,
    status: false,
  },
  {
    id: 9,
    fromAddress: "123 Main St, New York",
    deliveryAddress: "123 Park Rd, Chicago",
    container: "20 f",
    weight: 16,
    price: 487,
    status: false,
  },
  {
    id: 10,
    fromAddress: "123 First St, Los Angeles",
    deliveryAddress: "456 First St, Chicago",
    container: "20 f",
    weight: 41,
    price: 304,
    status: true,
  },
  {
    id: 11,
    fromAddress: "456 Main St, Los Angeles",
    deliveryAddress: "456 Main St, New York",
    container: "20 f",
    weight: 40,
    price: 906,
    status: true,
  },
  {
    id: 12,
    fromAddress: "123 Oak Ave, Chicago",
    deliveryAddress: "123 First St, Los Angeles",
    container: "40 f",
    weight: 78,
    price: 244,
    status: false,
  },
  {
    id: 13,
    fromAddress: "123 Park Rd, Chicago",
    deliveryAddress: "789 Main St, Houston",
    container: "20 f",
    weight: 90,
    price: 379,
    status: false,
  },
  {
    id: 14,
    fromAddress: "456 Park Rd, Chicago",
    deliveryAddress: "789 Park Rd, Chicago",
    container: "40 f",
    weight: 20,
    price: 545,
    status: false,
  },
  {
    id: 15,
    fromAddress: "123 Main St, New York",
    deliveryAddress: "123 Park Rd, New York",
    container: "40 f",
    weight: 40,
    price: 270,
    status: true,
  },
  {
    id: 16,
    fromAddress: "456 Oak Ave, Los Angeles",
    deliveryAddress: "456 Park Rd, New York",
    container: "20 f",
    weight: 40,
    price: 440,
    status: false,
  },
  {
    id: 17,
    fromAddress: "456 First St, New York",
    deliveryAddress: "123 First St, Chicago",
    container: "20 f",
    weight: 62,
    price: 692,
    status: false,
  },
  {
    id: 18,
    fromAddress: "123 Park Rd, Los Angeles",
    deliveryAddress: "123 Main St, Chicago",
    container: "20 f",
    weight: 14,
    price: 777,
    status: false,
  },
  {
    id: 19,
    fromAddress: "789 First St, Los Angeles",
    deliveryAddress: "456 Main St, Los Angeles",
    container: "20 f + 20 f",
    weight: 60,
    price: 205,
    status: false,
  },
  {
    id: 20,
    fromAddress: "789 Main St, Chicago",
    deliveryAddress: "456 Main St, Chicago",
    container: "40 f",
    weight: 7,
    price: 320,
    status: false,
  },
  {
    id: 21,
    fromAddress: "789 Park Rd, Los Angeles",
    deliveryAddress: "123 Park Rd, Los Angeles",
    container: "40 f",
    weight: 5,
    price: 819,
    status: false,
  },
  {
    id: 22,
    fromAddress: "456 Main St, New York",
    deliveryAddress: "789 Park Rd, New York",
    container: "20 f + 20 f",
    weight: 74,
    price: 318,
    status: false,
  },
  {
    id: 23,
    fromAddress: "789 Park Rd, New York",
    deliveryAddress: "789 Main St, Chicago",
    container: "20 f + 20 f",
    weight: 3,
    price: 145,
    status: false,
  },
  {
    id: 24,
    fromAddress: "789 Oak Ave, New York",
    deliveryAddress: "123 Main St, Houston",
    container: "40 f",
    weight: 84,
    price: 458,
    status: true,
  },
  {
    id: 25,
    fromAddress: "123 First St, Houston",
    deliveryAddress: "789 Park Rd, Houston",
    container: "20 f + 20 f",
    weight: 37,
    price: 126,
    status: false,
  },
  {
    id: 26,
    fromAddress: "789 Park Rd, New York",
    deliveryAddress: "123 Main St, New York",
    container: "40 f",
    weight: 85,
    price: 893,
    status: false,
  },
  {
    id: 27,
    fromAddress: "789 Main St, Houston",
    deliveryAddress: "456 Oak Ave, Los Angeles",
    container: "20 f",
    weight: 90,
    price: 957,
    status: true,
  },
  {
    id: 28,
    fromAddress: "123 First St, Los Angeles",
    deliveryAddress: "789 Main St, Chicago",
    container: "20 f",
    weight: 96,
    price: 706,
    status: false,
  },
  {
    id: 29,
    fromAddress: "456 Oak Ave, Chicago",
    deliveryAddress: "123 Park Rd, Los Angeles",
    container: "20 f + 20 f",
    weight: 51,
    price: 842,
    status: false,
  },
  {
    id: 30,
    fromAddress: "456 Main St, Los Angeles",
    deliveryAddress: "789 Oak Ave, Los Angeles",
    container: "20 f + 20 f",
    weight: 89,
    price: 473,
    status: true,
  },
  {
    id: 31,
    fromAddress: "789 Park Rd, Chicago",
    deliveryAddress: "456 Oak Ave, Houston",
    container: "20 f + 20 f",
    weight: 80,
    price: 991,
    status: true,
  },
  {
    id: 32,
    fromAddress: "456 Park Rd, Chicago",
    deliveryAddress: "123 Oak Ave, Chicago",
    container: "20 f + 20 f",
    weight: 18,
    price: 689,
    status: false,
  },
  {
    id: 33,
    fromAddress: "456 Main St, Houston",
    deliveryAddress: "123 First St, Los Angeles",
    container: "20 f",
    weight: 22,
    price: 551,
    status: true,
  },
  {
    id: 34,
    fromAddress: "123 Oak Ave, Los Angeles",
    deliveryAddress: "123 Oak Ave, New York",
    container: "20 f + 20 f",
    weight: 76,
    price: 481,
    status: false,
  },
  {
    id: 35,
    fromAddress: "789 First St, Houston",
    deliveryAddress: "123 Park Rd, Houston",
    container: "20 f + 20 f",
    weight: 11,
    price: 154,
    status: true,
  },
  {
    id: 36,
    fromAddress: "456 First St, New York",
    deliveryAddress: "123 Main St, Chicago",
    container: "20 f + 20 f",
    weight: 13,
    price: 831,
    status: false,
  },
  {
    id: 37,
    fromAddress: "456 Oak Ave, Los Angeles",
    deliveryAddress: "789 First St, New York",
    container: "20 f + 20 f",
    weight: 86,
    price: 901,
    status: true,
  },
  {
    id: 38,
    fromAddress: "789 First St, New York",
    deliveryAddress: "123 Main St, Los Angeles",
    container: "40 f",
    weight: 57,
    price: 504,
    status: false,
  },
  {
    id: 39,
    fromAddress: "456 Park Rd, Chicago",
    deliveryAddress: "123 Oak Ave, Chicago",
    container: "20 f",
    weight: 100,
    price: 850,
    status: false,
  },
  {
    id: 40,
    fromAddress: "456 Park Rd, New York",
    deliveryAddress: "789 Park Rd, New York",
    container: "20 f + 20 f",
    weight: 9,
    price: 445,
    status: false,
  },
  {
    id: 41,
    fromAddress: "123 First St, Chicago",
    deliveryAddress: "789 Park Rd, Houston",
    container: "20 f",
    weight: 52,
    price: 102,
    status: true,
  },
  {
    id: 42,
    fromAddress: "123 Oak Ave, Chicago",
    deliveryAddress: "123 Oak Ave, Chicago",
    container: "20 f",
    weight: 87,
    price: 658,
    status: true,
  },
  {
    id: 43,
    fromAddress: "456 First St, Houston",
    deliveryAddress: "456 Oak Ave, Chicago",
    container: "40 f",
    weight: 3,
    price: 671,
    status: true,
  },
  {
    id: 44,
    fromAddress: "456 Oak Ave, New York",
    deliveryAddress: "123 Main St, Chicago",
    container: "40 f",
    weight: 15,
    price: 415,
    status: false,
  },
  {
    id: 45,
    fromAddress: "123 First St, New York",
    deliveryAddress: "789 Main St, Houston",
    container: "20 f + 20 f",
    weight: 23,
    price: 979,
    status: false,
  },
  {
    id: 46,
    fromAddress: "456 First St, New York",
    deliveryAddress: "123 Main St, Houston",
    container: "20 f",
    weight: 67,
    price: 196,
    status: false,
  },
  {
    id: 47,
    fromAddress: "789 Park Rd, Chicago",
    deliveryAddress: "123 Park Rd, Houston",
    container: "40 f",
    weight: 62,
    price: 935,
    status: false,
  },
  {
    id: 48,
    fromAddress: "123 Main St, Chicago",
    deliveryAddress: "123 Park Rd, Chicago",
    container: "20 f",
    weight: 90,
    price: 975,
    status: true,
  },
  {
    id: 49,
    fromAddress: "456 Main St, Los Angeles",
    deliveryAddress: "456 Main St, Chicago",
    container: "40 f",
    weight: 2,
    price: 830,
    status: false,
  },
  {
    id: 50,
    fromAddress: "123 Oak Ave, Chicago",
    deliveryAddress: "123 Oak Ave, Houston",
    container: "20 f",
    weight: 9,
    price: 561,
    status: false,
  },
  {
    id: 51,
    fromAddress: "123 Main St, Los Angeles",
    deliveryAddress: "789 First St, Los Angeles",
    container: "20 f + 20 f",
    weight: 34,
    price: 217,
    status: false,
  },
  {
    id: 52,
    fromAddress: "456 Main St, Houston",
    deliveryAddress: "123 Park Rd, Los Angeles",
    container: "40 f",
    weight: 40,
    price: 579,
    status: false,
  },
  {
    id: 53,
    fromAddress: "456 Main St, Houston",
    deliveryAddress: "456 Oak Ave, New York",
    container: "20 f + 20 f",
    weight: 35,
    price: 215,
    status: true,
  },
  {
    id: 54,
    fromAddress: "789 Main St, Chicago",
    deliveryAddress: "456 Oak Ave, Houston",
    container: "20 f",
    weight: 89,
    price: 257,
    status: false,
  },
  {
    id: 55,
    fromAddress: "789 Park Rd, Chicago",
    deliveryAddress: "789 First St, Houston",
    container: "20 f + 20 f",
    weight: 68,
    price: 113,
    status: true,
  },
  {
    id: 56,
    fromAddress: "123 Main St, New York",
    deliveryAddress: "123 Oak Ave, Chicago",
    container: "40 f",
    weight: 74,
    price: 746,
    status: true,
  },
  {
    id: 57,
    fromAddress: "789 First St, New York",
    deliveryAddress: "456 First St, Houston",
    container: "20 f",
    weight: 24,
    price: 195,
    status: false,
  },
  {
    id: 58,
    fromAddress: "456 Main St, Chicago",
    deliveryAddress: "789 Park Rd, Houston",
    container: "20 f",
    weight: 86,
    price: 458,
    status: false,
  },
  {
    id: 59,
    fromAddress: "456 Main St, Los Angeles",
    deliveryAddress: "789 Oak Ave, Los Angeles",
    container: "20 f",
    weight: 71,
    price: 251,
    status: false,
  },
  {
    id: 60,
    fromAddress: "456 First St, Chicago",
    deliveryAddress: "123 Main St, New York",
    container: "20 f + 20 f",
    weight: 5,
    price: 657,
    status: false,
  },
  {
    id: 61,
    fromAddress: "789 First St, Houston",
    deliveryAddress: "123 Oak Ave, Los Angeles",
    container: "20 f + 20 f",
    weight: 87,
    price: 877,
    status: true,
  },
  {
    id: 62,
    fromAddress: "789 Park Rd, New York",
    deliveryAddress: "456 Oak Ave, Chicago",
    container: "20 f",
    weight: 8,
    price: 696,
    status: false,
  },
  {
    id: 63,
    fromAddress: "456 First St, Chicago",
    deliveryAddress: "456 Main St, Chicago",
    container: "40 f",
    weight: 61,
    price: 652,
    status: true,
  },
  {
    id: 64,
    fromAddress: "123 Park Rd, New York",
    deliveryAddress: "789 First St, Houston",
    container: "40 f",
    weight: 5,
    price: 948,
    status: false,
  },
  {
    id: 65,
    fromAddress: "456 Oak Ave, New York",
    deliveryAddress: "123 Main St, New York",
    container: "20 f + 20 f",
    weight: 51,
    price: 586,
    status: false,
  },
  {
    id: 66,
    fromAddress: "456 Oak Ave, New York",
    deliveryAddress: "789 Main St, New York",
    container: "40 f",
    weight: 78,
    price: 722,
    status: true,
  },
  {
    id: 67,
    fromAddress: "789 Main St, Houston",
    deliveryAddress: "123 First St, Los Angeles",
    container: "40 f",
    weight: 59,
    price: 339,
    status: true,
  },
  {
    id: 68,
    fromAddress: "123 First St, New York",
    deliveryAddress: "456 First St, Houston",
    container: "20 f + 20 f",
    weight: 70,
    price: 202,
    status: true,
  },
  {
    id: 69,
    fromAddress: "456 Park Rd, Chicago",
    deliveryAddress: "123 Oak Ave, Chicago",
    container: "20 f + 20 f",
    weight: 61,
    price: 790,
    status: true,
  },
  {
    id: 70,
    fromAddress: "123 Main St, New York",
    deliveryAddress: "789 Oak Ave, Los Angeles",
    container: "20 f",
    weight: 29,
    price: 976,
    status: true,
  },
  {
    id: 71,
    fromAddress: "789 Park Rd, Chicago",
    deliveryAddress: "456 Main St, Los Angeles",
    container: "20 f",
    weight: 6,
    price: 360,
    status: true,
  },
  {
    id: 72,
    fromAddress: "123 Oak Ave, New York",
    deliveryAddress: "456 Oak Ave, New York",
    container: "40 f",
    weight: 39,
    price: 856,
    status: false,
  },
  {
    id: 73,
    fromAddress: "123 Main St, Los Angeles",
    deliveryAddress: "456 First St, Chicago",
    container: "40 f",
    weight: 5,
    price: 854,
    status: false,
  },
  {
    id: 74,
    fromAddress: "456 First St, Los Angeles",
    deliveryAddress: "456 Oak Ave, New York",
    container: "40 f",
    weight: 1,
    price: 121,
    status: false,
  },
  {
    id: 75,
    fromAddress: "789 Park Rd, Houston",
    deliveryAddress: "789 Main St, New York",
    container: "20 f + 20 f",
    weight: 70,
    price: 940,
    status: false,
  },
  {
    id: 76,
    fromAddress: "789 Oak Ave, Los Angeles",
    deliveryAddress: "123 Park Rd, Chicago",
    container: "20 f + 20 f",
    weight: 91,
    price: 126,
    status: false,
  },
  {
    id: 77,
    fromAddress: "456 Park Rd, Houston",
    deliveryAddress: "123 Oak Ave, Los Angeles",
    container: "40 f",
    weight: 98,
    price: 719,
    status: true,
  },
  {
    id: 78,
    fromAddress: "456 Main St, New York",
    deliveryAddress: "456 Park Rd, Houston",
    container: "40 f",
    weight: 73,
    price: 303,
    status: true,
  },
  {
    id: 79,
    fromAddress: "456 Park Rd, New York",
    deliveryAddress: "123 Oak Ave, Los Angeles",
    container: "20 f",
    weight: 52,
    price: 154,
    status: true,
  },
  {
    id: 80,
    fromAddress: "789 Oak Ave, New York",
    deliveryAddress: "789 Park Rd, Los Angeles",
    container: "40 f",
    weight: 20,
    price: 659,
    status: true,
  },
  {
    id: 81,
    fromAddress: "456 First St, New York",
    deliveryAddress: "123 First St, Houston",
    container: "20 f + 20 f",
    weight: 14,
    price: 863,
    status: true,
  },
  {
    id: 82,
    fromAddress: "789 Park Rd, Houston",
    deliveryAddress: "789 Oak Ave, New York",
    container: "20 f",
    weight: 46,
    price: 307,
    status: false,
  },
  {
    id: 83,
    fromAddress: "123 Park Rd, New York",
    deliveryAddress: "456 Oak Ave, Los Angeles",
    container: "40 f",
    weight: 63,
    price: 366,
    status: false,
  },
  {
    id: 84,
    fromAddress: "789 Park Rd, Los Angeles",
    deliveryAddress: "789 Oak Ave, Chicago",
    container: "20 f + 20 f",
    weight: 55,
    price: 650,
    status: true,
  },
  {
    id: 85,
    fromAddress: "123 Main St, New York",
    deliveryAddress: "456 First St, Los Angeles",
    container: "40 f",
    weight: 61,
    price: 691,
    status: false,
  },
  {
    id: 86,
    fromAddress: "789 Oak Ave, Chicago",
    deliveryAddress: "123 Oak Ave, Chicago",
    container: "40 f",
    weight: 43,
    price: 884,
    status: true,
  },
  {
    id: 87,
    fromAddress: "123 Main St, Los Angeles",
    deliveryAddress: "789 Main St, Houston",
    container: "20 f",
    weight: 33,
    price: 393,
    status: true,
  },
  {
    id: 88,
    fromAddress: "789 Main St, Houston",
    deliveryAddress: "123 First St, Houston",
    container: "20 f",
    weight: 61,
    price: 176,
    status: false,
  },
  {
    id: 89,
    fromAddress: "789 Main St, Houston",
    deliveryAddress: "789 Main St, Los Angeles",
    container: "20 f",
    weight: 79,
    price: 265,
    status: true,
  },
  {
    id: 90,
    fromAddress: "456 Oak Ave, Chicago",
    deliveryAddress: "789 Park Rd, Chicago",
    container: "40 f",
    weight: 81,
    price: 122,
    status: true,
  },
  {
    id: 91,
    fromAddress: "123 Oak Ave, Houston",
    deliveryAddress: "789 First St, Chicago",
    container: "20 f + 20 f",
    weight: 10,
    price: 348,
    status: true,
  },
  {
    id: 92,
    fromAddress: "123 Main St, Los Angeles",
    deliveryAddress: "789 Oak Ave, Houston",
    container: "20 f + 20 f",
    weight: 94,
    price: 967,
    status: false,
  },
  {
    id: 93,
    fromAddress: "456 Main St, Los Angeles",
    deliveryAddress: "456 Main St, Los Angeles",
    container: "20 f",
    weight: 16,
    price: 771,
    status: false,
  },
  {
    id: 94,
    fromAddress: "789 First St, Los Angeles",
    deliveryAddress: "456 Park Rd, Houston",
    container: "20 f",
    weight: 7,
    price: 740,
    status: true,
  },
  {
    id: 95,
    fromAddress: "456 First St, Chicago",
    deliveryAddress: "789 First St, New York",
    container: "20 f + 20 f",
    weight: 48,
    price: 781,
    status: false,
  },
  {
    id: 96,
    fromAddress: "789 Main St, New York",
    deliveryAddress: "456 First St, Chicago",
    container: "40 f",
    weight: 45,
    price: 950,
    status: false,
  },
  {
    id: 97,
    fromAddress: "456 Oak Ave, New York",
    deliveryAddress: "123 Main St, New York",
    container: "20 f",
    weight: 84,
    price: 315,
    status: true,
  },
  {
    id: 98,
    fromAddress: "456 Park Rd, Chicago",
    deliveryAddress: "456 Main St, Chicago",
    container: "20 f + 20 f",
    weight: 84,
    price: 533,
    status: false,
  },
  {
    id: 99,
    fromAddress: "456 Main St, Houston",
    deliveryAddress: "123 Park Rd, Los Angeles",
    container: "20 f + 20 f",
    weight: 33,
    price: 274,
    status: true,
  },
  {
    id: 100,
    fromAddress: "456 First St, Houston",
    deliveryAddress: "789 Oak Ave, New York",
    container: "20 f",
    weight: 71,
    price: 595,
    status: true,
  },
];
